---
- hosts: webserver
  become: yes
  tasks:
    - name: Ensure web directory exists
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy web app files
      copy:
        src: ../app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
        backup: yes
      notify: restart apache

    - name: Set correct permissions for web directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Verify Apache configuration
      command: apache2ctl configtest
      register: apache_config_test
      changed_when: false

    - name: Display Apache config test result
      debug:
        var: apache_config_test.stdout

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted