---
- hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache and required packages
      apt:
        name:
          - apache2
          - ufw
        state: present

    - name: Configure UFW firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '22'
        - '80'

    - name: Enable UFW firewall
      ufw:
        state: enabled

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove default Apache index page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started